services:
  samba:
    build: .
    image: custom-samba:latest
    environment:
      - USERNAME=admin
      - PASSWORD=changeme
      - SHARE_NAME=nas
    volumes:
      - ssd_volume:/mnt/ssd
    ports:
      - "139:139"
      - "445:445"
    deploy:
      placement:
        constraints:
          - node.labels.role == samba

volumes:
  ssd_volume:
    external: true
