port: 3000

bindIP: 0.0.0.0

db:
  type: postgres
  host: db
  port: 5432
  user: wiki
  pass: wikijsrocks
  db: wikijs

logLevel: info

ssl:
  enabled: true
  port: 3443
  provider: custom
  format: pem
  key: /ssl/privkey.pem
  cert: /ssl/cert.pem
