version: '3.8'

services:
  wikijs:
    build: .
    container_name: wikijs
    ports:
      - "3000:3000"
    volumes:
      - wikidata:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB=wikijs
      POSTGRES_USER=wiki
      POSTGRES_PASSWORD=strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  wikidata:
  pgdata:
