services:
  wikijs:
    build: .
    container_name: wikijs
    ports:
      - "3080:3000"
    volumes:
      - ./config.yml:/app/config.yml
      - wikidata:/app
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wikijs
      DB_USER: wiki
      DB_PASS: strongpassword
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    ports: 
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  wikidata:
  pgdata:
