services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute,video,graphics,utility]