services:
  mdwiki:
    build: .
    container_name: mdwiki
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - mdwiki-notes:/data/notes
      - mdwiki-classes:/data/classes

volumes:
  mdwiki-notes:
    external: true
  mdwiki-classes:
    external: true
