services:
  cpu-temp-api:
    image: mjanders6/cpu-temp-api:latest
    networks:
      - nodejs_network
    deploy:
      mode: global
    environment:
      - EULA=TRUE
      - PUID=1000
      - PGID=1000
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      # - ./server.js:/app/server.js
      # - ./ecosystem.config.js:/app/ecosystem.config.js
      - /sys/class/thermal:/sys/class/thermal
      - /etc/hostname:/etc/hostname


networks:
  nodejs_network:
    driver: overlay