services:
  cpu-temp-api:
    #image: localhost:5000/cpu-temp-api
    image: mjanders6/cpu-temp-api:latest
    container_name: cpu-temp-api
    deploy:
      mode: global
    network_mode: "host"  # Disables Swarm routing mesh
    environment:
      - EULA=TRUE
      - PUID=1000
      - PGID=1000
    ports:
      - "3000:3000"
    volumes:
      # - ./server.js:/app/server.js
      # - ./ecosystem.config.js:/app/ecosystem.config.js
      - /sys/class/thermal:/sys/class/thermal
    privileged: true
    restart: unless-stopped
