services:
  minecraft:
    image: mjanders6/minecraft:mod
    container_name: minecraft
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/127.0.0.1/25565"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

    environment:
      MC_UID: 1000
      MC_GID: 1000
      RCON_PASSWORD: ${RCON_PASSWORD}
      GAME_MODE: ${GAME_MODE}
      SERVER_IP: ${SERVER_IP}

    volumes:
      - backups_data:/server/backups
      - minecraft_mod:/server

    ports:
      - "25565:25565"
      - "24454:24454/udp"

volumes:
  backups_data:
    external: true
  minecraft_mod:
    external: true