services:
  nginx-rpi0:
    image: nginx:alpine
    configs:
      - source: rpi0-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi0.crt
        target: /etc/nginx/certs/server.crt
        mode: 0444
      - source: rpi0.key
        target: /etc/nginx/certs/server.key
        mode: 0400
    deploy:
      placement:
        constraints:
          - node.hostname == rpi0-server
    ports:
      - "80:80"
      - "443:443"

  nginx-rpi1:
    image: nginx:alpine
    configs:
      - source: rpi1-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi1.crt
        target: /etc/nginx/certs/server.crt
        mode: 0444
      - source: rpi1.key
        target: /etc/nginx/certs/server.key
        mode: 0400
    deploy:
      placement:
        constraints:
          - node.hostname == rpi1-server
    ports:
      - "81:80"
      - "444:443"

  nginx-rpi2:
    image: nginx:alpine
    configs:
      - source: rpi2-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi2.crt
        target: /etc/nginx/certs/server.crt
        mode: 0444
      - source: rpi2.key
        target: /etc/nginx/certs/server.key
        mode: 0400
    deploy:
      placement:
        constraints:
          - node.hostname == rpi2-server
    ports:
      - "82:80"
      - "445:443"

  nginx-rpi3:
    image: nginx:alpine
    configs:
      - source: rpi3-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi3.crt
        target: /etc/nginx/certs/server.crt
        mode: 0444
      - source: rpi3.key
        target: /etc/nginx/certs/server.key
        mode: 0400
    deploy:
      placement:
        constraints:
          - node.hostname == rpi3-server
    ports:
      - "83:80"
      - "446:443"

configs:
  rpi0-nginx.conf:
    external: true
  rpi1-nginx.conf:
    external: true
  rpi2-nginx.conf:
    external: true
  rpi3-nginx.conf:
    external: true

secrets:
  rpi0.crt:
    external: true
  rpi0.key:
    external: true
  rpi1.crt:
    external: true
  rpi1.key:
    external: true
  rpi2.crt:
    external: true
  rpi2.key:
    external: true
  rpi3.crt:
    external: true
  rpi3.key:
    external: true
