services:
  nginx_rpi0:
    image: nginx:alpine
    configs:
      - source: rpi0-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi0.crt
        target: /etc/ssl/certs/server.crt
      - source: rpi0.key
        target: /etc/ssl/private/server.key
    deploy:
      placement:
        constraints: [node.hostname == rpi0-server]
    ports:
      - target: 80
        published: 8080
        mode: host
      - target: 443
        published: 8443
        mode: host

  nginx_rpi1:
    image: nginx:alpine
    configs:
      - source: rpi1-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi1.crt
        target: /etc/ssl/certs/server.crt
      - source: rpi1.key
        target: /etc/ssl/private/server.key
    deploy:
      placement:
        constraints: [node.hostname == rpi1-server]
    ports:
      - target: 80
        published: 8080
        mode: host
      - target: 443
        published: 8443
        mode: host

  nginx_rpi2:
    image: nginx:alpine
    configs:
      - source: rpi2-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi2.crt
        target: /etc/ssl/certs/server.crt
      - source: rpi2.key
        target: /etc/ssl/private/server.key
    deploy:
      placement:
        constraints: [node.hostname == rpi2-server]
    ports:
      - target: 80
        published: 8080
        mode: host
      - target: 443
        published: 8443
        mode: host

  nginx_rpi3:
    image: nginx:alpine
    configs:
      - source: rpi3-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: rpi3.crt
        target: /etc/ssl/certs/server.crt
      - source: rpi3.key
        target: /etc/ssl/private/server.key
    deploy:
      placement:
        constraints: [node.hostname == rpi3-server]
    ports:
      - target: 80
        published: 8080
        mode: host
      - target: 443
        published: 8443
        mode: host

configs:
  rpi0-nginx.conf:
    external: true
  rpi1-nginx.conf:
    external: true
  rpi2-nginx.conf:
    external: true
  rpi3-nginx.conf:
    external: true

secrets:
  rpi0.crt:
    external: true
  rpi0.key:
    external: true
  rpi1.crt:
    external: true
  rpi1.key:
    external: true
  rpi2.crt:
    external: true
  rpi2.key:
    external: true
  rpi3.crt:
    external: true
  rpi3.key:
    external: true
