services:
  nginx:
    image: nginx:alpine
    deploy:
      mode: global  # One nginx container per node
    configs:
      - source: ${NODE_NAME}-nginx.conf
        target: /etc/nginx/nginx.conf
    secrets:
      - source: ${NODE_NAME}.crt
        target: /etc/ssl/certs/server.crt
      - source: ${NODE_NAME}.key
        target: /etc/ssl/private/server.key
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/conf.d  # Use default conf.d if needed
    environment:
      - NODE_NAME={{.Node.Hostname}}
    configs:
      - default.conf
configs:
  rpi0-nginx.conf:
    external: true
  rpi1-nginx.conf:
    external: true
  rpi2-nginx.conf:
    external: true
  rpi3-nginx.conf:
    external: true
  default.conf:
    file: ./configs/default.conf

secrets:
  rpi0.crt:
    external: true
  rpi0.key:
    external: true
  rpi1.crt:
    external: true
  rpi1.key:
    external: true
  rpi2.crt:
    external: true
  rpi2.key:
    external: true
  rpi3.crt:
    external: true
  rpi3.key:
    external: true
