version: "3.9"

services:
  dockhand:
    image: fnsys/dockhand:latest
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host  # Ensures Dockhand is accessed on the manager node only
    networks:
      - dockhand_net
    environment:
      LOG_LEVEL: info
      DOCKHAND_ENVIRONMENTS: swarm
      DOCKHAND_ENV_swarm_NAME: "Docker Swarm Cluster"
      DOCKHAND_ENV_swarm_DESCRIPTION: "Environment for all Hawser agents running in the Docker Swarm"
      DOCKHAND_ENV_swarm_DISCOVERY: "hawser"
      DOCKHAND_ENV_swarm_DEFAULT: "true"
      DOCKHAND_AGENT_TOKEN_FILE: /run/secrets/dockhand_agent_token
    volumes:
      - dockhand_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - dockhand_agent_token
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  hawser-agent:
    image: ghcr.io/finsys/hawser:latest
    ports:
      - target: 2376
        published: 2376
        protocol: tcp
        mode: host  # Critical for correct host association
    networks:
      - dockhand_net
    environment:
      DOCKHAND_SERVER: http://dockhand:3000
      DOCKHAND_ENVIRONMENT: swarm
      DOCKHAND_AGENT_TOKEN_FILE: /run/secrets/dockhand_agent_token
      AGENT_MODE: swarm
      NODE_ID: "{{.Node.ID}}"
      NODE_HOSTNAME: "{{.Node.Hostname}}"
      #NODE_IP: "{{.Node.Address}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - dockhand_agent_token
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

networks:
  dockhand_net:
    driver: overlay
    attachable: true

volumes:
  dockhand_data:
    external: true #driver: local

secrets:
  dockhand_agent_token:
    external: true